# Generated by Django 4.2.5 on 2024-03-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_remove_house_color_house_address_house_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color_code',
        ),
    ]
