# Generated by Django 4.2.5 on 2024-03-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_category_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
